import { useState } from 'react';
import { DEFAULT_HARNESS, harnessApi, type EnvironmentReport, type HarnessOptions } from '../lib/harness-api';
import { MemoryPanel } from './MemoryPanel';
import './harness.css';

export function HarnessPanel({ graphId, options, onChange, onDesign, disabled }: { graphId: string; options: HarnessOptions; onChange: (value: HarnessOptions) => void; onDesign: () => void; disabled?: boolean }) {
  const [tab, setTab] = useState('workflow');
  return <section className="editor-page harness-panel" aria-label="Engineering harness">
    <header className="editor-page-heading"><div><h1>Engineering harness</h1><p>Turn an idea into an editable, evidence-backed system proposal.</p></div></header>
    <div className="harness-tabs" role="tablist" aria-label="Harness sections">{['workflow', 'memory', 'environment'].map((id) => <button type="button" role="tab" key={id} aria-selected={tab === id} onClick={() => setTab(id)}>{id[0].toUpperCase() + id.slice(1)}</button>)}</div>
    {tab === 'workflow' && <div className="harness-section">
      <ol className="harness-flow"><li><strong>Define</strong><span>Start with one idea and connect supporting nodes or references.</span></li><li><strong>Refine</strong><span>An orchestrator prepares a brief; a specialist checks tradeoffs; the composer suggests nodes.</span></li><li><strong>Review</strong><span>Keep useful work, change the scope, and refine assumptions in chat.</span></li><li><strong>Execute</strong><span>Approve the final plan. Follow commands, artifacts, and verification at each checkpoint.</span></li></ol>
      <label className="harness-check"><input type="checkbox" checked={options.enabled} disabled={disabled} onChange={(e) => onChange({ ...options, enabled: e.target.checked })} />Use the engineering harness in chat</label>
      <label>Delivery scope<select aria-label="Engineering profile" value={options.profile} disabled={disabled} onChange={(e) => onChange({ ...options, profile: e.target.value as HarnessOptions['profile'] })}><option value="poc">PoC · test the central assumption</option><option value="mvp">MVP · deliver a useful complete journey</option><option value="production">Production · include operational readiness</option></select></label>
      <p className="harness-muted">{options.profile === 'poc' ? 'Prefer fixtures, the smallest stack, and explicit shortcuts. Separate feasibility evidence from release readiness.' : options.profile === 'mvp' ? 'Cover the main user journey, contracts, persistence, tests, and setup. Add complexity only when the requirements justify it.' : 'Include deployment, migrations, security, observability, recovery, performance, and ownership where relevant.'}</p>
      <label>Total token budget<input aria-label="Harness token budget" type="number" min="4000" max="100000" step="1000" disabled={disabled} value={options.tokenBudget} onChange={(e) => onChange({ ...options, tokenBudget: Math.min(100000, Math.max(4000, Number(e.target.value) || 4000)) })} /></label>
      <p className="harness-muted">Includes up to three model calls and provider runtime context. CLI providers can add substantial input overhead. Estimates and reported usage are shown separately; this is not a billing limit.</p>
      <label>Engineering conventions<textarea aria-label="Engineering conventions" rows={6} maxLength={8000} value={options.conventions} disabled={disabled} onChange={(e) => onChange({ ...options, conventions: e.target.value })} /></label>
      <div className="harness-actions"><button type="button" disabled={disabled} onClick={onDesign}>Design the system in chat</button><button type="button" className="quiet-button" disabled={disabled} onClick={() => onChange(DEFAULT_HARNESS)}>Reset workflow defaults</button></div>
      <details><summary>What the proposal should cover</summary><p>UI and interaction patterns, fixture data, local and server state, API style, database, architecture boundaries, types and generated contracts, testing, accessibility, environments, README.md, spec.md, AGENTS.md, relevant skills, and setup guides. Suggestions must explain their fit and distinguish decisions from open questions.</p><p>Frameworks, languages, and versions follow your requirements and available evidence. Installed agents are editable starting points; tools and execution providers still need real support on this machine.</p></details>
    </div>}
    {tab === 'memory' && <MemoryPanel key={graphId} graphId={graphId} />}
    {tab === 'environment' && <EnvironmentPanel key={graphId} graphId={graphId} />}
  </section>;
}

function EnvironmentPanel({ graphId }: { graphId: string }) {
  const [report, setReport] = useState<EnvironmentReport>(); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const inspect = async () => { setBusy(true); setError(''); try { setReport((await harnessApi.environment(graphId)).environment); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } };
  return <div className="harness-section"><h2>Execution environment</h2><p>Check available tools before committing to a stack. Detection runs fixed version commands; it does not install packages or prove a toolchain can build your project.</p><button type="button" disabled={busy} onClick={() => void inspect()}>{busy ? 'Checking tools…' : 'Inspect local environment'}</button>{error && <p role="alert" className="harness-error">{error}</p>}{report && <><p>{report.summary}</p><p className="harness-muted">{report.workspacePath || 'No folder bound'} · {new Date(report.checkedAt).toLocaleString()}</p>{report.execution && <div><h3>Workspace executor · {report.execution.providerId}</h3><p>{report.execution.ready ? "Available" : "Needs setup"} · {report.execution.detail}</p>{report.execution.setupOptions?.map((option) => <p key={option}>{option}</p>)}</div>}<div className="environment-tools">{report.tools.map((tool) => <details key={tool.id}><summary><strong>{tool.label}</strong><span>{tool.available ? tool.version || 'Available' : 'Not found'}</span></summary><p>{tool.detail}</p>{tool.command && <code>{Array.isArray(tool.command) ? tool.command.join(' ') : tool.command}</code>}{(tool.setupOptions || []).map((option, i) => <p key={i}>{typeof option === 'string' ? option : <>{option.label || option.description}{option.url && <> · <a href={option.url} target="_blank" rel="noreferrer">Setup documentation</a></>}{option.command && <code>{option.command}</code>}</>}</p>)}</details>)}</div></>}</div>;
}
