import { useEffect, useState } from 'react';
import { harnessApi, type MemoryRecord, type MemorySettings } from '../lib/harness-api';

export function MemoryPanel({ graphId }: { graphId: string }) {
  const [records, setRecords] = useState<MemoryRecord[]>([]); const [settings, setSettings] = useState<MemorySettings>({ provider: 'local', endpoint: '', remoteRecallEnabled: false });
  const [content, setContent] = useState(''); const [editId, setEditId] = useState(''); const [kind, setKind] = useState('decision'); const [key, setKey] = useState('');
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const [compactions, setCompactions] = useState<Array<{ id: string; [key: string]: unknown }>>([]);
  const reload = async () => { const [items, config, summaries] = await Promise.all([harnessApi.memory(graphId), harnessApi.memorySettings(graphId), harnessApi.compactions(graphId)]); setRecords(items.items); setSettings(config.settings); setCompactions(summaries.items); };
  useEffect(() => { let live = true; void Promise.all([harnessApi.memory(graphId), harnessApi.memorySettings(graphId), harnessApi.compactions(graphId)]).then(([items, config, summaries]) => { if (live) { setRecords(items.items); setSettings(config.settings); setCompactions(summaries.items); } }).catch((e: Error) => { if (live) setError(e.message); }); return () => { live = false; }; }, [graphId]);
  const act = async (fn: () => Promise<unknown>, message = '') => { setBusy(true); setError(''); setNotice(''); try { const result = await fn(); await reload(); const warning = result && typeof result === 'object' && 'warning' in result ? String(result.warning || '') : ''; setNotice(warning || message); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } };
  return <div className="harness-section"><h2>Project memory</h2><p>Keep decisions and constraints that future conversations should reuse. Only current confirmed or validated records enter recalled context. Original conversations remain available after compaction.</p>
    {error && <p className="harness-error" role="alert">{error}</p>}{notice && <p role="status">{notice}</p>}
    <div className="memory-editor"><label>Memory type<select aria-label="Memory type" value={kind} onChange={(e) => setKind(e.target.value)}><option value="decision">Decision</option><option value="constraint">Constraint</option><option value="preference">Preference</option><option value="open_question">Open question</option><option value="lesson">Lesson</option></select></label><label>{editId ? 'Edit memory' : 'New project memory'}<textarea aria-label="Memory content" value={content} maxLength={8000} rows={4} onChange={(e) => setContent(e.target.value)} placeholder="For example: The first release uses a modular monolith and REST. Revisit GraphQL only if client needs justify it." /></label><div className="harness-actions"><button type="button" disabled={busy || !content.trim()} onClick={() => void act(async () => { const input = { kind, content: content.trim(), validation: { state: 'user_confirmed', reason: 'Explicitly saved by the user.' } }; if (editId) await harnessApi.updateMemory(graphId, editId, input); else await harnessApi.remember(graphId, input); setContent(''); setEditId(''); }, 'Project memory saved.')}>{editId ? 'Save confirmed revision' : 'Save confirmed memory'}</button>{editId && <button type="button" onClick={() => { setEditId(''); setContent(''); }}>Cancel edit</button>}</div></div>
    <div className="memory-records" aria-label="Project memory records">{!records.length && <p className="harness-muted">No project memory yet. Save a decision here or retain a useful chat response for review.</p>}{records.map((record) => <article key={record.id}><header><strong>{record.kind.replaceAll('_', ' ')}</strong><span>{record.validation.state.replaceAll('_', ' ')}</span></header><p>{record.content}</p>{record.validation.reason && <small>{record.validation.reason}</small>}<details><summary>Provenance and scope</summary><pre>{JSON.stringify({ nodeIds: record.nodeIds, provenance: record.provenance, digest: record.digest }, null, 2)}</pre></details><div className="harness-actions"><button type="button" disabled={busy} onClick={() => { setEditId(record.id); setContent(record.content); setKind(record.kind); }}>Edit</button>{record.validation.state !== 'user_confirmed' && <button type="button" disabled={busy || record.validation.state === 'stale'} onClick={() => void act(() => harnessApi.updateMemory(graphId, record.id, { validation: { state: 'user_confirmed', reason: 'Reviewed and confirmed by the user.' } }))}>Confirm</button>}<button type="button" disabled={busy} onClick={() => void act(() => harnessApi.updateMemory(graphId, record.id, { validation: { state: 'rejected', reason: 'Excluded by the user.' } }))}>Exclude</button><button type="button" disabled={busy} onClick={() => void act(() => harnessApi.forget(graphId, record.id), 'Memory excluded from future recall.')}>Forget</button>{settings.provider !== 'local' && <button type="button" disabled={busy || !['validated', 'user_confirmed'].includes(record.validation.state)} onClick={() => void act(() => harnessApi.sync(graphId, record.id), 'Sync request finished. Review provider status before relying on remote availability.')}>Send this record to {settings.provider}</button>}</div></article>)}</div>
    <details><summary>Context compaction · {compactions.length} snapshots</summary><p>Bounded summaries retain references to the original messages. A summary does not prove that a decision or implementation is correct.</p>{compactions.map((item) => <details key={item.id}><summary>Snapshot {item.id.slice(0, 8)}</summary><pre>{JSON.stringify(item, null, 2)}</pre></details>)}</details>
    <details><summary>Optional memory provider</summary><p className="harness-muted">Status: {String(settings.remoteStatus || settings.provider)}{settings.warning ? ` · ${settings.warning}` : ''}</p><p>Local memory works without a service. Connecting a service does not send records automatically. Each record has a separate send action; remote recall uses only locally validated matching provenance.</p><label>Memory provider<select aria-label="Memory provider" value={settings.provider} onChange={(e) => { setKey(''); setSettings({ ...settings, provider: e.target.value as MemorySettings['provider'], endpoint: '', remoteRecallEnabled: false }); }}><option value="local">Local PostgreSQL</option><option value="hindsight">Hindsight</option><option value="mem0">mem0 Open Source</option></select></label>{settings.provider !== 'local' && <><label>Service endpoint<input aria-label="Memory endpoint" value={settings.endpoint || ''} placeholder={settings.provider === 'hindsight' ? 'http://127.0.0.1:8888' : 'http://127.0.0.1:8000'} onChange={(e) => { setKey(''); setSettings({ ...settings, endpoint: e.target.value }); }} /></label><label>Session API key<input aria-label="Memory API key" type="password" autoComplete="off" value={key} onChange={(e) => setKey(e.target.value)} placeholder={settings.apiKeyConfigured ? 'Configured for this session' : 'Optional for local services'} /></label><label className="harness-check"><input type="checkbox" checked={settings.remoteRecallEnabled} onChange={(e) => setSettings({ ...settings, remoteRecallEnabled: e.target.checked })} />Allow scoped queries to this memory service</label></>}<button type="button" disabled={busy} onClick={() => void act(async () => { await harnessApi.saveMemorySettings(graphId, { provider: settings.provider, endpoint: settings.endpoint, remoteRecallEnabled: settings.remoteRecallEnabled, ...(key ? { apiKey: key } : {}) }); setKey(''); }, 'Memory settings saved.')}>Save memory settings</button></details>
  </div>;
}
