import { useEffect, useRef, useState } from 'react';
import { request } from '../lib/api';
import type { EngineeringAgent, ProviderStatus, TopicNode } from '../lib/types';
interface SkillChoice { id: string; name: string; enabled?: boolean; archived?: boolean }
export function NodeConfiguration({ node, nodes = [], agents, providers, readOnly, onChange }: { node: TopicNode; nodes?: TopicNode[]; agents: EngineeringAgent[]; providers: ProviderStatus[]; readOnly?: boolean; onChange: (patch: Partial<TopicNode>) => void }) {
  const [skills, setSkills] = useState<SkillChoice[]>([]);
  const [error, setError] = useState('');
  useEffect(() => { let active = true; request<{ items?: SkillChoice[]; skills?: SkillChoice[] }>('/api/catalog/skills').then((value) => { if (active) { setSkills(value.items ?? value.skills ?? []); setError(''); } }).catch((cause) => { if (active) setError(cause.message); }); return () => { active = false; }; }, []);
  return <div className="node-configuration">
    <h2>Execution configuration</h2><p className="muted">Empty overrides inherit the selected agent and workspace defaults. The next plan pins the effective configuration.</p>
    <div className="configuration-grid">
      <label>Agent<select aria-label="Node agent" disabled={readOnly} value={node.agentId ?? ''} onChange={(event) => onChange({ agentId: event.target.value || undefined })}><option value="">Automatic assignment</option>{node.agentId && !agents.some((agent) => agent.id === node.agentId) && <option value={node.agentId} disabled>{node.agentId} (unavailable)</option>}{agents.map((agent) => <option key={agent.id} value={agent.id} disabled={agent.status !== 'ACTIVE'}>{agent.name}{agent.status !== 'ACTIVE' ? ' (disabled)' : ''}</option>)}</select></label>
      <label>Provider<select aria-label="Node provider" disabled={readOnly} value={node.providerId ?? ''} onChange={(event) => onChange({ providerId: event.target.value || undefined })}><option value="">Inherit agent / workspace provider</option>{providers.filter((item) => ['codex-cli', 'openai-api', 'anthropic-api', 'ollama'].includes(item.id)).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
      <label>Model override<input aria-label="Node model" disabled={readOnly} value={node.model ?? ''} placeholder="Inherit agent / provider model" onChange={(event) => onChange({ model: event.target.value || undefined })} /></label>
      <label>Group<input aria-label="Node group" disabled={readOnly} value={node.group ?? ''} placeholder="Optional group" onChange={(event) => onChange({ group: event.target.value || undefined })} /></label>
      <label>Timeout (seconds)<input type="number" min="1" max="3600" aria-label="Node timeout seconds" disabled={readOnly} value={node.budgets?.timeoutMs === undefined ? '' : node.budgets.timeoutMs / 1000} placeholder="Inherit" onChange={(event) => onChange({ budgets: { ...node.budgets, timeoutMs: event.target.value ? Number(event.target.value) * 1000 : undefined } })} /></label>
      <label>Maximum attempts<input type="number" min="1" max="10" aria-label="Node maximum attempts" disabled={readOnly} value={node.budgets?.maxAttempts ?? ''} placeholder="Inherit" onChange={(event) => onChange({ budgets: { ...node.budgets, maxAttempts: event.target.value ? Number(event.target.value) : undefined } })} /></label>
    </div>
    <label className="checkbox-label"><input type="checkbox" checked={node.breakpoint ?? false} disabled={readOnly} onChange={(event) => onChange({ breakpoint: event.target.checked })} />Pause before this node starts</label>
    <details className="configuration-details"><summary>Peer review <span>{node.review?.required ? `${node.review.reviewerNodeIds.length} reviewers required` : 'Off'}</span></summary>
      <p className="muted">Require evidence-based review of this node's receipt and artifacts before dependent work continues. Each reviewer makes one independent pass; these choices do not add execution dependencies.</p>
      <label className="checkbox-label"><input type="checkbox" checked={node.review?.required ?? false} disabled={readOnly} onChange={(event) => onChange({ review: { ...node.review, reviewerNodeIds: node.review?.reviewerNodeIds ?? [], required: event.target.checked } })} />Require peer review before accepting this node</label>
      {node.review?.required && <>
        <p className="muted">Select one to four other nodes. Assign an agent preset to each reviewer node and choose a connected review provider below. The ordinary node execution provider stays unchanged. Reviews use no tools or workspace writes; Codex CLI cannot act as a reviewer.</p>
        <label>Review provider<select aria-label="Node review provider" disabled={readOnly} value={node.review.providerId ?? ''} onChange={(event) => onChange({ review: { ...node.review!, providerId: event.target.value ? event.target.value as NonNullable<TopicNode['review']>['providerId'] : undefined } })}><option value="">Inherit reviewer agent API default</option>{providers.filter((provider) => ['openai-api', 'anthropic-api', 'ollama'].includes(provider.id)).map((provider) => <option key={provider.id} value={provider.id}>{provider.name}</option>)}</select></label>
        {!node.review.reviewerNodeIds.length && <p role="status" className="inline-error">Select at least one reviewer before planning.</p>}
        <div className="skill-choices">{nodes.filter((candidate) => candidate.id !== node.id).map((candidate) => {
          const selected = node.review?.reviewerNodeIds.includes(candidate.id) ?? false;
          return <label key={candidate.id}><input type="checkbox" aria-label={`Reviewer ${candidate.title}`} checked={selected} disabled={readOnly || (!selected && (node.review?.reviewerNodeIds.length ?? 0) >= 4)} onChange={(event) => onChange({ review: { ...node.review, required: true, reviewerNodeIds: event.target.checked ? [...new Set([...(node.review?.reviewerNodeIds ?? []), candidate.id])] : (node.review?.reviewerNodeIds ?? []).filter((id) => id !== candidate.id) } })} />{candidate.title}</label>;
        })}</div>
        {node.review.reviewerNodeIds.filter((id) => id === node.id || !nodes.some((candidate) => candidate.id === id)).map((id) => <label className="checkbox-label" key={id}><input type="checkbox" checked disabled={readOnly} onChange={() => onChange({ review: { ...node.review, required: true, reviewerNodeIds: node.review!.reviewerNodeIds.filter((candidate) => candidate !== id) } })} />{id === node.id ? 'This node cannot review itself' : `Missing reviewer: ${id}`} (remove selection)</label>)}
      </>}
    </details>
    <details className="configuration-details"><summary>Inputs, outputs, and acceptance criteria</summary><ListField key={`${node.id}-inputs`} label="Inputs" value={node.inputs} disabled={readOnly} onChange={(inputs) => onChange({ inputs })} /><ListField key={`${node.id}-outputs`} label="Outputs" value={node.outputs} disabled={readOnly} onChange={(outputs) => onChange({ outputs })} /><ListField key={`${node.id}-criteria`} label="Acceptance criteria" value={node.acceptanceCriteria} disabled={readOnly} onChange={(acceptanceCriteria) => onChange({ acceptanceCriteria })} /></details>
    <details className="configuration-details"><summary>Skills <span>{node.skills?.length ? `${node.skills.length} selected` : 'Automatic'}</span></summary><p className="muted">Choose explicit skills to override automatic routing for this node.</p>{error && <p role="alert" className="inline-error">Skills could not be loaded: {error}</p>}<div className="skill-choices">{skills.filter((skill) => (skill.enabled !== false && !skill.archived) || node.skills?.includes(skill.id)).map((skill) => <label key={skill.id}><input type="checkbox" disabled={readOnly} checked={node.skills?.includes(skill.id) ?? false} onChange={(event) => onChange({ skills: event.target.checked ? [...(node.skills ?? []), skill.id] : node.skills?.filter((id) => id !== skill.id) })} />{skill.name}{skill.enabled === false || skill.archived ? ' (unavailable — remove override)' : ''}</label>)}</div><button type="button" className="quiet-button" disabled={readOnly || !node.skills?.length} onClick={() => onChange({ skills: [] })}>Use automatic routing</button></details>
  </div>;
}
function ListField({ label, value = [], disabled, onChange }: { label: string; value?: string[]; disabled?: boolean; onChange: (values: string[]) => void }) {
  const [text, setText] = useState(value.join('\n'));
  const field = useRef<HTMLTextAreaElement>(null);
  useEffect(() => { if (document.activeElement !== field.current) setText(value.join('\n')); }, [value]);
  return <label>{label}<textarea ref={field} aria-label={`Node ${label.toLowerCase()}`} value={text} disabled={disabled} rows={3} placeholder="One item per line" onChange={(event) => { setText(event.target.value); onChange(event.target.value.split('\n').map((line) => line.trim()).filter(Boolean)); }} /></label>;
}
