import { randomUUID } from 'node:crypto';

export const DEFAULT_CHAT_TEMPLATES = [
  { id: 'discuss', name: 'Discuss', action: 'discuss', prompt: 'Explain these nodes, their context, assumptions, and open questions.' },
  { id: 'refine', name: 'Refine nodes', action: 'refine', prompt: 'Refine these nodes into clear objectives, context, inputs, outputs, and acceptance criteria. Propose reviewable changes.' },
  { id: 'fact-check', name: 'Fact-check', action: 'fact-check', prompt: 'Fact-check the claims in these nodes against the attached evidence. Cite specific evidence excerpts and identify missing evidence.' },
  { id: 'relationships', name: 'Suggest relationships', action: 'refine', prompt: 'Suggest useful relationships between the selected nodes. Explain the direction, type, and which relationships affect execution.' },
  { id: 'develop', name: 'Develop', action: 'develop', prompt: 'Develop an implementation brief for these nodes with scoped objectives and acceptance criteria. Propose draft changes for review before planning and execution.' },
  { id: 'explain-run', name: 'Explain an execution', action: 'discuss', prompt: 'Explain the attached execution results and what is required to continue. If no execution evidence is attached, say what is missing.' },
];
const parse = (value, fallback) => { try { return JSON.parse(value); } catch { return fallback; } };
const now = () => new Date().toISOString();

export class ChatStore {
  constructor(database) {
    this.database = database;
    database.exec(`
      CREATE TABLE IF NOT EXISTS chat_conversations (
        id TEXT PRIMARY KEY, graph_id TEXT NOT NULL REFERENCES graphs(id) ON DELETE CASCADE,
        title TEXT NOT NULL, node_ids_json TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL
      );
      CREATE TABLE IF NOT EXISTS chat_messages (
        id TEXT PRIMARY KEY, conversation_id TEXT NOT NULL REFERENCES chat_conversations(id) ON DELETE CASCADE,
        role TEXT NOT NULL, content TEXT NOT NULL, status TEXT NOT NULL, action TEXT NOT NULL,
        provider_id TEXT, model TEXT, context_json TEXT NOT NULL, result_json TEXT NOT NULL,
        created_at TEXT NOT NULL, updated_at TEXT NOT NULL,
        sequence BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE
      );
      CREATE TABLE IF NOT EXISTS chat_proposals (
        id TEXT PRIMARY KEY, graph_id TEXT NOT NULL REFERENCES graphs(id) ON DELETE CASCADE,
        message_id TEXT NOT NULL REFERENCES chat_messages(id) ON DELETE CASCADE,
        status TEXT NOT NULL, proposal_json TEXT NOT NULL, created_at TEXT NOT NULL, applied_revision INTEGER
      );
      CREATE INDEX IF NOT EXISTS chat_graph_idx ON chat_conversations(graph_id, updated_at);
      CREATE INDEX IF NOT EXISTS chat_message_idx ON chat_messages(conversation_id, created_at);
    `);
    database.prepare("UPDATE chat_messages SET status='interrupted',updated_at=? WHERE status='running'").run(now());
  }
  conversation(row) { return row ? { id: row.id, graphId: row.graph_id, title: row.title, nodeIds: parse(row.node_ids_json, []), createdAt: row.created_at, updatedAt: row.updated_at } : null; }
  getConversation(id) { return this.conversation(this.database.prepare('SELECT * FROM chat_conversations WHERE id=?').get(id)); }
  listConversations(graphId) { return this.database.prepare('SELECT * FROM chat_conversations WHERE graph_id=? ORDER BY updated_at DESC').all(graphId).map((row) => this.conversation(row)); }
  createConversation(graphId, nodeIds, title) {
    const id = randomUUID(); const time = now();
    this.database.prepare('INSERT INTO chat_conversations VALUES (?,?,?,?,?,?)').run(id, graphId, title, JSON.stringify(nodeIds), time, time);
    return this.getConversation(id);
  }
  message(row) { return row ? { id: row.id, conversationId: row.conversation_id, role: row.role, content: row.content, status: row.status, action: row.action, providerId: row.provider_id, model: row.model, context: parse(row.context_json, {}), ...parse(row.result_json, {}), createdAt: row.created_at, updatedAt: row.updated_at } : null; }
  getMessage(id) { return this.message(this.database.prepare('SELECT * FROM chat_messages WHERE id=?').get(id)); }
  listMessages(conversationId) { return this.database.prepare('SELECT * FROM chat_messages WHERE conversation_id=? ORDER BY sequence ASC').all(conversationId).map((row) => this.message(row)); }
  createMessage(conversationId, { role, content = '', status = 'completed', action = 'discuss', providerId = null, model = null, context = {} }) {
    const id = randomUUID(); const time = now();
    this.database.prepare('INSERT INTO chat_messages (id,conversation_id,role,content,status,action,provider_id,model,context_json,result_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)').run(id, conversationId, role, content, status, action, providerId, model, JSON.stringify(context), '{}', time, time);
    this.database.prepare('UPDATE chat_conversations SET updated_at=? WHERE id=?').run(time, conversationId);
    return this.getMessage(id);
  }
  updateMessage(id, { content, status, ...result }) {
    this.database.prepare('UPDATE chat_messages SET content=?,status=?,result_json=?,updated_at=? WHERE id=?').run(content, status, JSON.stringify(result), now(), id);
    return this.getMessage(id);
  }
  saveProposal(messageId, proposal) {
    const id = randomUUID(); const complete = { ...proposal, id, status: 'pending', messageId };
    this.database.prepare('INSERT INTO chat_proposals VALUES (?,?,?,?,?,?,?)').run(id, proposal.graphId, messageId, 'pending', JSON.stringify(complete), now(), null);
    return complete;
  }
  getProposal(id) {
    const row = this.database.prepare('SELECT * FROM chat_proposals WHERE id=?').get(id);
    return row ? { ...parse(row.proposal_json, {}), status: row.status, appliedRevision: row.applied_revision } : null;
  }
  markApplied(id, revision) { this.database.prepare("UPDATE chat_proposals SET status='applied',applied_revision=? WHERE id=?").run(revision, id); }
}
