import { randomUUID } from 'node:crypto';
import { HARNESS_STAGES } from './harness_profiles.mjs';
const now = () => new Date().toISOString();
export class HarnessStore {
  constructor(database) {
    this.database = database;
    database.exec(`
      CREATE TABLE IF NOT EXISTS engineering_harness_runs (
        id TEXT PRIMARY KEY, graph_id TEXT NOT NULL REFERENCES graphs(id) ON DELETE CASCADE,
        conversation_id TEXT NOT NULL REFERENCES chat_conversations(id) ON DELETE CASCADE,
        message_id TEXT NOT NULL REFERENCES chat_messages(id) ON DELETE CASCADE,
        status TEXT NOT NULL, input_digest TEXT NOT NULL, request_json TEXT NOT NULL,
        state_json TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL,
        sequence BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE
      );
      CREATE TABLE IF NOT EXISTS engineering_harness_cache (
        cache_key TEXT PRIMARY KEY, graph_id TEXT NOT NULL REFERENCES graphs(id) ON DELETE CASCADE,
        result_json TEXT NOT NULL, created_at TEXT NOT NULL
      );
      CREATE INDEX IF NOT EXISTS harness_message_idx ON engineering_harness_runs(message_id);
    `);
    database.prepare("UPDATE engineering_harness_runs SET status='interrupted',updated_at=? WHERE status='running'").run(now());
  }
  get(id) {
    const row = this.database.prepare('SELECT * FROM engineering_harness_runs WHERE id=?').get(id);
    return row ? { id: row.id, graphId: row.graph_id, conversationId: row.conversation_id, messageId: row.message_id, status: row.status, inputDigest: row.input_digest, request: JSON.parse(row.request_json), ...JSON.parse(row.state_json), createdAt: row.created_at, updatedAt: row.updated_at } : null;
  }
  forMessage(messageId) { const row = this.database.prepare('SELECT id FROM engineering_harness_runs WHERE message_id=? ORDER BY sequence DESC LIMIT 1').get(messageId); return row ? this.get(row.id) : null; }
  create({ graphId, conversationId, messageId, inputDigest, request }) {
    const id = randomUUID(); const time = now();
    this.database.prepare('INSERT INTO engineering_harness_runs (id,graph_id,conversation_id,message_id,status,input_digest,request_json,state_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)').run(id, graphId, conversationId, messageId, 'running', inputDigest, JSON.stringify(request), JSON.stringify({ handoffs: [], completedStages: [], nextStage: 'brief', usage: { estimatedInputTokens: 0, estimatedOutputTokens: 0, providerReported: {}, cachedStages: 0 } }), time, time);
    return this.get(id);
  }
  update(id, { status, ...state }) {
    const previous = this.get(id);
    const { handoffs, completedStages, nextStage, usage, error, failedAttempts } = previous;
    this.database.prepare('UPDATE engineering_harness_runs SET status=?,state_json=?,updated_at=? WHERE id=?').run(status || previous.status, JSON.stringify({ handoffs, completedStages, nextStage, usage, error, failedAttempts, ...state }), now(), id);
    return this.get(id);
  }
  cache(key) { const row = this.database.prepare('SELECT result_json FROM engineering_harness_cache WHERE cache_key=?').get(key); return row ? JSON.parse(row.result_json) : null; }
  checkpoint(runId, stage, result, key, { cached = false } = {}) {
    const run = this.get(runId); const handoffs = [...run.handoffs.filter((item) => item.stage !== stage), result.handoff];
    const completedStages = [...new Set([...run.completedStages, stage])];
    this.database.exec('BEGIN');
    try {
      if (!cached) this.database.prepare('INSERT INTO engineering_harness_cache VALUES (?,?,?,?) ON CONFLICT(cache_key) DO UPDATE SET graph_id=excluded.graph_id,result_json=excluded.result_json,created_at=excluded.created_at').run(key, run.graphId, JSON.stringify(result), now());
      this.update(runId, { handoffs, completedStages, nextStage: HARNESS_STAGES.find((item) => !completedStages.includes(item)) ?? null, usage: result.runUsage });
      this.database.prepare('DELETE FROM engineering_harness_cache WHERE graph_id=? AND cache_key NOT IN (SELECT cache_key FROM engineering_harness_cache WHERE graph_id=? ORDER BY created_at DESC LIMIT 128)').run(run.graphId, run.graphId);
      this.database.exec('COMMIT');
    } catch (error) { this.database.exec('ROLLBACK'); throw error; }
  }
  public(run) {
    if (!run) return null;
    const input = run.request.inputManifest;
    const contextManifest = input ? { draftRevision: input.promptContext.draftRevision, scopeNodeIds: input.promptContext.scopeNodeIds, agentPins: Object.values(input.agents).map(({ id, configDigest, promptDigest }) => ({ id, configDigest, promptDigest })), skillPins: input.promptContext.skills?.map(({ id, contentDigest, packageDigest }) => ({ id, contentDigest, packageDigest })), evidenceDigest: input.promptContext.evidenceDigest, historyDigest: input.conversationContext.digest, memoryDigest: input.promptContext.memory?.digest, providerId: input.providerId, model: input.providerProfile.model } : undefined;
    return { id: run.id, status: run.status, profile: run.request.config.profile, completedStages: run.completedStages, nextStage: run.nextStage, handoffs: run.handoffs, usage: run.usage, failedAttempts: run.failedAttempts || [], contextDigest: run.inputDigest, contextManifest, tokenBudget: run.request.config.tokenBudget, budgetBasis: 'Text token estimates; provider-reported usage is recorded separately. No monetary guarantee.', canResume: ['interrupted', 'stopped', 'failed'].includes(run.status) && Boolean(run.nextStage), error: run.error, createdAt: run.createdAt, updatedAt: run.updatedAt };
  }
}
