import { randomUUID } from 'node:crypto';

export class HarnessMemoryStore {
  constructor(database) {
    this.database = database;
    database.exec(`
      CREATE TABLE IF NOT EXISTS harness_memory (
        id TEXT PRIMARY KEY, graph_id TEXT NOT NULL REFERENCES graphs(id) ON DELETE CASCADE,
        record_json TEXT NOT NULL, updated_at TEXT NOT NULL
      );
      CREATE INDEX IF NOT EXISTS harness_memory_graph ON harness_memory(graph_id,updated_at);
      CREATE TABLE IF NOT EXISTS harness_memory_settings (
        graph_id TEXT PRIMARY KEY REFERENCES graphs(id) ON DELETE CASCADE, settings_json TEXT NOT NULL
      );
      CREATE TABLE IF NOT EXISTS harness_compactions (
        id TEXT PRIMARY KEY, graph_id TEXT NOT NULL REFERENCES graphs(id) ON DELETE CASCADE,
        conversation_id TEXT NOT NULL, digest TEXT NOT NULL, manifest_json TEXT NOT NULL,
        sequence BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
        UNIQUE(graph_id,conversation_id,digest)
      );
    `);
  }
  list(graphId) { return this.database.prepare('SELECT record_json FROM harness_memory WHERE graph_id=? ORDER BY updated_at DESC,id').all(graphId).map((row) => JSON.parse(row.record_json)); }
  get(graphId, id) { const row = this.database.prepare('SELECT record_json FROM harness_memory WHERE graph_id=? AND id=?').get(graphId, id); return row ? JSON.parse(row.record_json) : null; }
  put(record) {
    this.database.prepare('INSERT INTO harness_memory VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET record_json=excluded.record_json,updated_at=excluded.updated_at').run(record.id, record.graphId, JSON.stringify(record), record.updatedAt);
    return record;
  }
  forget(graphId, id) { return this.database.prepare('DELETE FROM harness_memory WHERE graph_id=? AND id=?').run(graphId, id).changes > 0; }
  settings(graphId) { const row = this.database.prepare('SELECT settings_json FROM harness_memory_settings WHERE graph_id=?').get(graphId); return row ? JSON.parse(row.settings_json) : {}; }
  saveSettings(graphId, settings) { this.database.prepare('INSERT INTO harness_memory_settings VALUES(?,?) ON CONFLICT(graph_id) DO UPDATE SET settings_json=excluded.settings_json').run(graphId, JSON.stringify(settings)); }
  compactions(graphId) { return this.database.prepare('SELECT manifest_json FROM harness_compactions WHERE graph_id=? ORDER BY sequence DESC LIMIT 100').all(graphId).map((row) => JSON.parse(row.manifest_json)); }
  compact(manifest) {
    const existing = this.database.prepare('SELECT manifest_json FROM harness_compactions WHERE graph_id=? AND conversation_id=? AND digest=?').get(manifest.graphId, manifest.conversationId, manifest.digest);
    if (existing) return JSON.parse(existing.manifest_json);
    const result = { id: randomUUID(), ...manifest, createdAt: new Date().toISOString() };
    this.database.prepare('INSERT INTO harness_compactions (id,graph_id,conversation_id,digest,manifest_json) VALUES(?,?,?,?,?)').run(result.id, result.graphId, result.conversationId, result.digest, JSON.stringify(result));
    return result;
  }
}
